import streamlit as st
import numpy as np
import pandas as pd
from fpdf import FPDF
from datetime import datetime
import io

st.set_page_config(page_title="Manufacturing Quote Risk Analyzer", page_icon="🔧", layout="wide")

st.title("🔧 Manufacturing Quote Risk Analyzer")
st.markdown("*Get data-driven confidence intervals for your manufacturing quotes*")
st.markdown("---")

# Sidebar inputs
st.sidebar.header("📊 Job Parameters")

job_name = st.sidebar.text_input("Job Name (optional)", placeholder="e.g., Bracket-2024-001")

st.sidebar.subheader("💰 Material Costs")
material_cost = st.sidebar.number_input("Base Material Cost ($)", min_value=100, max_value=50000, value=3500, step=100)
material_uncertainty = st.sidebar.slider("Material Cost Uncertainty (%)", min_value=5, max_value=40, value=12)
waste_pct = st.sidebar.slider("Expected Material Waste (%)", min_value=5, max_value=30, value=10)

st.sidebar.subheader("⏱ Labor Estimates")
setup_hours = st.sidebar.number_input("Setup Time (hours)", min_value=0.5, max_value=40.0, value=4.0, step=0.5)
machining_hours = st.sidebar.number_input("Machining Time (hours)", min_value=1.0, max_value=500.0, value=35.0, step=1.0)
finishing_hours = st.sidebar.number_input("Finishing Time (hours)", min_value=0.5, max_value=40.0, value=5.0, step=0.5)
labor_uncertainty = st.sidebar.slider("Labor Time Uncertainty (%)", min_value=10, max_value=50, value=20)
labor_rate = st.sidebar.number_input("Labor Rate ($/hr)", min_value=30, max_value=200, value=75, step=5)

st.sidebar.subheader("🔩 Other Costs")
tooling_cost = st.sidebar.number_input("Tooling/Consumables ($)", min_value=50, max_value=5000, value=400, step=50)
subcontractor_cost = st.sidebar.number_input("Subcontractor Cost ($)", min_value=0, max_value=10000, value=800, step=100)
rework_probability = st.sidebar.slider("Rework Probability (%)", min_value=0, max_value=50, value=15)

st.sidebar.subheader("📈 Business Factors")
overhead_multiplier = st.sidebar.number_input("Overhead Multiplier", min_value=1.0, max_value=3.0, value=1.35, step=0.05)
profit_margin = st.sidebar.number_input("Profit Margin Multiplier", min_value=1.0, max_value=2.0, value=1.15, step=0.05)

n_simulations = 10000

# PDF Generation Function
def generate_pdf(job_name, results):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    
    # Title
    pdf.cell(0, 10, "Manufacturing Quote Risk Analysis Report", ln=True, align="C")
    pdf.ln(10)
    
    # Job Info
    pdf.set_font("Arial", "", 12)
    if job_name:
        pdf.cell(0, 10, f"Job Name: {job_name}", ln=True)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.ln(10)
    
    # Key Results
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Key Results", ln=True)
    pdf.set_font("Arial", "", 12)
    pdf.ln(5)
    
    pdf.cell(90, 10, "Expected Cost:", border=1)
    pdf.cell(0, 10, f"${results['mean']:,.0f}", border=1, ln=True)
    
    pdf.cell(90, 10, "Median (50%):", border=1)
    pdf.cell(0, 10, f"${results['median']:,.0f}", border=1, ln=True)
    
    pdf.cell(90, 10, "Conservative (75%):", border=1)
    pdf.cell(0, 10, f"${results['p75']:,.0f}", border=1, ln=True)
    
    pdf.cell(90, 10, "High Confidence (90%):", border=1)
    pdf.cell(0, 10, f"${results['p90']:,.0f}", border=1, ln=True)
    
    pdf.ln(10)
    
    # Recommendations
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Quoting Recommendations", ln=True)
    pdf.set_font("Arial", "", 11)
    pdf.ln(5)
    
    pdf.multi_cell(0, 8, f"COMPETITIVE QUOTE (50% confidence): ${results['median']:,.0f}\nUse for competitive bidding and repeat customers.\nRisk: 50/50 chance of cost overrun.")
    pdf.ln(5)
    
    pdf.multi_cell(0, 8, f"CONSERVATIVE QUOTE (75% confidence): ${results['p75']:,.0f}\nUse for new customers and complex jobs.\nRisk premium: ${results['p75'] - results['median']:,.0f}")
    pdf.ln(10)
    
    # Detailed Statistics
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Detailed Statistics", ln=True)
    pdf.set_font("Arial", "", 12)
    pdf.ln(5)
    
    pdf.cell(90, 10, "10th Percentile:", border=1)
    pdf.cell(0, 10, f"${results['p10']:,.0f}", border=1, ln=True)
    
    pdf.cell(90, 10, "25th Percentile:", border=1)
    pdf.cell(0, 10, f"${results['p25']:,.0f}", border=1, ln=True)
    
    pdf.cell(90, 10, "50th Percentile (Median):", border=1)
    pdf.cell(0, 10, f"${results['median']:,.0f}", border=1, ln=True)
    
    pdf.cell(90, 10, "75th Percentile:", border=1)
    pdf.cell(0, 10, f"${results['p75']:,.0f}", border=1, ln=True)
    
    pdf.cell(90, 10, "90th Percentile:", border=1)
    pdf.cell(0, 10, f"${results['p90']:,.0f}", border=1, ln=True)
    
    pdf.ln(15)
    
    # Footer
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, "Generated by Manufacturing Quote Risk Analyzer - Monte Carlo simulation (10,000 iterations)", align="C")
    
    return pdf.output(dest='S').encode('latin-1')

# Main App Logic
if st.sidebar.button("🚀 Run Risk Analysis", type="primary"):
    
    with st.spinner("Running Monte Carlo simulation..."):
        
        # Material simulation
        mat_std = material_cost * (material_uncertainty / 100)
        raw_material = np.random.normal(material_cost, mat_std, n_simulations)
        waste = np.random.triangular(waste_pct*0.5, waste_pct, waste_pct*2, n_simulations) / 100
        material_total = raw_material * (1 + waste)
        
        # Labor simulation
        setup_std = setup_hours * (labor_uncertainty / 100)
        machining_std = machining_hours * (labor_uncertainty / 100)
        finishing_std = finishing_hours * (labor_uncertainty / 100)
        
        setup_sim = np.random.normal(setup_hours, setup_std, n_simulations)
        machining_sim = np.random.normal(machining_hours, machining_std, n_simulations)
        finishing_sim = np.random.normal(finishing_hours, finishing_std, n_simulations)
        
        total_labor_hours = setup_sim + machining_sim + finishing_sim
        
        # Overtime risk
        overtime = np.random.random(n_simulations) < 0.10
        effective_rate = np.where(overtime, labor_rate * 1.5, labor_rate)
        labor_cost = total_labor_hours * effective_rate
        
        # Rework simulation
        needs_rework = np.random.random(n_simulations) < (rework_probability / 100)
        rework_hours = np.where(needs_rework, np.random.uniform(5, 15, n_simulations), 0)
        rework_cost = rework_hours * labor_rate
        
        # Total cost
        direct_costs = material_total + labor_cost + tooling_cost + subcontractor_cost + rework_cost
        total_quote = direct_costs * overhead_multiplier * profit_margin
        
        # Calculate statistics
        mean_cost = total_quote.mean()
        median_cost = np.percentile(total_quote, 50)
        p10 = np.percentile(total_quote, 10)
        p25 = np.percentile(total_quote, 25)
        p75 = np.percentile(total_quote, 75)
        p90 = np.percentile(total_quote, 90)
        
        # Store results
        results = {
            'mean': mean_cost,
            'median': median_cost,
            'p10': p10,
            'p25': p25,
            'p75': p75,
            'p90': p90
        }
        
        st.session_state['results'] = results
        st.session_state['total_quote'] = total_quote
        
    st.success("✅ Analysis Complete!")
    
    # Key Results
    st.subheader("📊 Key Results")
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.metric("Expected Cost", f"${mean_cost:,.0f}")
    with col2:
        st.metric("Median (50%)", f"${median_cost:,.0f}")
    with col3:
        st.metric("Conservative (75%)", f"${p75:,.0f}", delta=f"+${p75-median_cost:,.0f}")
    with col4:
        st.metric("High Confidence (90%)", f"${p90:,.0f}", delta=f"+${p90-median_cost:,.0f}")
    
    # Distribution chart
    st.subheader("📈 Cost Distribution")
    chart_df = pd.DataFrame({'Quote Price': total_quote})
    st.bar_chart(chart_df['Quote Price'].value_counts().sort_index().head(50), height=400)
    
    # Recommendations
    st.subheader("💡 Quoting Recommendations")
    
    rec_col1, rec_col2 = st.columns(2)
    
    with rec_col1:
        st.info(f"🎯 COMPETITIVE QUOTE**\n\n### ${median_cost:,.0f}\n\n- 50% confidence level\n- Use for: Competitive bidding\n- Risk: 50/50 chance of overrun")
    
    with rec_col2:
        st.success(f"✅ CONSERVATIVE QUOTE**\n\n### ${p75:,.0f}\n\n- 75% confidence level\n- Use for: New customers, complex jobs\n- Risk premium: ${p75-median_cost:,.0f}")
    
    # Statistics table
    st.subheader("📋 Detailed Statistics")
    stats_df = pd.DataFrame({
        'Percentile': ['10th', '25th', '50th (Median)', '75th', '90th'],
        'Quote Price': [f"${p10:,.0f}", f"${p25:,.0f}", f"${median_cost:,.0f}", f"${p75:,.0f}", f"${p90:,.0f}"]
    })
    st.dataframe(stats_df, use_container_width=True, hide_index=True)
    
    # PDF Download
    st.subheader("📄 Export Report")
    pdf_bytes = generate_pdf(job_name if job_name else "Untitled Job", results)
    
    st.download_button(
        label="⬇ Download PDF Report",
        data=pdf_bytes,
        file_name=f"risk_analysis_{job_name.replace(' ', '') if job_name else 'report'}{datetime.now().strftime('%Y%m%d')}.pdf",
        mime="application/pdf",
        type="primary"
    )

else:
    st.info("👈 *Adjust parameters in sidebar and click 'Run Risk Analysis'*")
    
    st.markdown("""
    ### How to Use:
    
    1. Enter job parameters in sidebar
    2. Optionally add a job name
    3. Click 'Run Risk Analysis'
    4. Download professional PDF report
    
    ### Features:
    - ✅ Monte Carlo simulation (10,000 iterations)
    - ✅ Multiple confidence levels
    - ✅ Professional PDF reports
    - ✅ Conservative & competitive quotes
    """)

st.markdown("---")
st.markdown("Manufacturing Quote Risk Analyzer v2.0")
